# Site settings
title: "Nick Chao"
description: "Nick Chao's personal website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Nick Chao"
resume_title: "Aspiring Platform Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email: "yuchen.chao@nyu.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: ""
resume_contact_address: ""

resume_header_contact_info: ""
display_header_contact_info: "false"

resume_header_intro: "<b>Nick codes, runs, and writes stuff</b>. At work, he's worn different hats: Software Engineer, Cloud Support, and DevOps/Infra. At leisure, he runs marathon and is somewhat addicted to <a href='https://www.strava.com/athletes/136261530'>Strava</a>. He also writes blogs on <a href='https://medium.com/@nicksome.yc'>Medium</a> and <a href='https://www.threads.net/@nicksome_yc'>threads</a>.</p>See his <a href='https://github.com/nicksome168'>Github</a> and <a href='https://www.linkedin.com/in/nick-chao'>LinkedIn</a> for more."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work: "no"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: false
resume_section_skills: false
resume_section_recognition: true
resume_section_links: false
resume_section_associations: false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
# resume_github_url: "https://github.com/nicksome168"
# resume_linkedin_url: "https://www.linkedin.com/in/nick-chao"
# resume_medium_url: "https://medium.com/@nicksome.yc"
# resume_print_social_links: true
google_analytics: G-1L72ZZB9X3

# Design settings
resume_theme: default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
